#!/bin/bash
#-------------------------------------------------------------------------------
#Created by barbinjulien mailto: barbinjulien[at]gmail[dot]com
#-------------------------------------------------------------------------------
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

#-------------------------------------------------------------------------------
# Strongly inspired by: https://github.com/helmuthdu/aui

#-------------------------------------------------------------------------------
# Run this script after your first boot with archlinux (as root)

if [[ -f `pwd`/funclib ]]; then
  source funclib
else
  echo "missing file: funclib"
  exit 1
fi

print_title "https://wiki.archlinux.org/index.php/Installation_guide"
print_info "This Install Scripts are a set of Bash scripts that simplify Arch installation."
check_boot_system
check_connection
pause_function