#!/bin/bash
#-------------------------------------------------------------------------------
#Created by barbinjulien mailto: barbinjulien[at]gmail[dot]com
#-------------------------------------------------------------------------------
#This program is free software: you can redistribute it and/or modify
#it under the terms of the GNU General Public License as published by
#the Free Software Foundation, either version 3 of the License, or
#(at your option) any later version.
#
#This program is distributed in the hope that it will be useful,
#but WITHOUT ANY WARRANTY; without even the implied warranty of
#MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#GNU General Public License for more details.
#
#You should have received a copy of the GNU General Public License
#along with this program.  If not, see <http://www.gnu.org/licenses/>.

#-------------------------------------------------------------------------------
# Strongly inspired by: https://github.com/helmuthdu/aui

#-------------------------------------------------------------------------------
# Run this script after your first boot with archlinux (as root)

if [[ -f `pwd`/funclib ]]; then
  source funclib
else
  echo "missing file: funclib"
  exit 1
fi

print_title "https://wiki.archlinux.org/index.php/Installation_guide"
print_info "This Install Scripts are a set of Bash scripts that simplify Arch installation."
check_boot_system
check_connection
check_trim
# pacman -Sy ## Not needed for the moment
pause_function

while true
do
  print_title "ARCHLINUX INSTALL - https://github.com/barbinjulien/ArchInstall"
  echo " 1) $(mainmenu_item "${checklist[1]}"  "Select Keymap"            "${KEYMAP}" )"
  echo " 2) $(mainmenu_item "${checklist[2]}"  "Select Editor"            "${EDITOR}" )"
  echo " 3) $(mainmenu_item "${checklist[3]}"  "Configure Mirrorlist"     "${country_name} (${country_code})" )"
  echo ""
  echo " d) Done"
  echo ""
  read_input_options
  for OPT in ${OPTIONS[@]}; do
    case "$OPT" in
      1)
        select_keymap
        checklist[1]=1
        ;;
      2)
        select_editor
        checklist[2]=1
        ;;
      3)
        configure_mirrorlist
        checklist[3]=1
        ;;
      "d")
        donesetup
        #finish
        ;;
      *)
        invalid_option
        ;;
    esac
  done
done